### ISSUE TITLE
make it consistent

### ISSUE THREAD

**Issue by BobOdencock** [Pigpog/discord-rich-presence-cli#3]
got it done without yalls help thanks

**Comment by Pigpog** [comment]
Judging by your [copy-pasted issue](https://github.com/JackyTea/Custom-Discord-Rich-Presence/issues/1) and [the other one](https://github.com/ThatOneCalculator/DiscordRPCMaker/discussions/130) you seem to want a normal presence, not a rich presence. That world of warcraft status is the result of Discord just detecting that the game was running, not by a rich presence component of the game itself. The Discord client is constantly checking the information of what programs you're running and checking a list of titles to see if it should show up or not. If you really want a custom presence of this style (albeit without the image), simply go to Discord's Settings page -> Activity Status and then click Add Game.

Closing because this issue is irrelevant to this _rich_ presence program.
